-- MySQL Script generated by MySQL Workbench
-- Sat Jan 30 16:15:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema peliculasdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `peliculasdb` ;

-- -----------------------------------------------------
-- Schema peliculasdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `peliculasdb` DEFAULT CHARACTER SET utf8 ;
USE `peliculasdb` ;

-- -----------------------------------------------------
-- Table `peliculasdb`.`Peliculas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculasdb`.`Peliculas` ;

CREATE TABLE IF NOT EXISTS `peliculasdb`.`Peliculas` (
  `idPelicula` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `annio` VARCHAR(45) NOT NULL,
  `duracion` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `sinopsis` VARCHAR(500) NOT NULL,
  `imagen` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idPelicula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculasdb`.`Actores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculasdb`.`Actores` ;

CREATE TABLE IF NOT EXISTS `peliculasdb`.`Actores` (
  `idActor` INT NOT NULL AUTO_INCREMENT,
  `fechaNacimiento` DATE NOT NULL,
  `paisNacimiento` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idActor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculasdb`.`Peliculas_has_Actores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculasdb`.`Peliculas_has_Actores` ;

CREATE TABLE IF NOT EXISTS `peliculasdb`.`Peliculas_has_Actores` (
  `Peliculas_idPelicula` INT NOT NULL,
  `Actores_idActor` INT NOT NULL,
  PRIMARY KEY (`Peliculas_idPelicula`, `Actores_idActor`),
  INDEX `fk_Peliculas_has_Actores_Actores1_idx` (`Actores_idActor` ASC) VISIBLE,
  INDEX `fk_Peliculas_has_Actores_Peliculas_idx` (`Peliculas_idPelicula` ASC) VISIBLE,
  CONSTRAINT `fk_Peliculas_has_Actores_Peliculas`
    FOREIGN KEY (`Peliculas_idPelicula`)
    REFERENCES `peliculasdb`.`Peliculas` (`idPelicula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Peliculas_has_Actores_Actores1`
    FOREIGN KEY (`Actores_idActor`)
    REFERENCES `peliculasdb`.`Actores` (`idActor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;